name: "Internxt WebDAV"
description: "Mount your Internxt Drive as a WebDAV server for easy file access"
version: 0.0.1
slug: "internxt-webdav"
url: "https://github.com/MyUncleSam/hassio-addons"
arch:
  - "amd64"
  - "aarch64"
init: false
ports:
  3005/tcp: "127.0.0.1:3005"
ports_description:
  3005/tcp: "WebDAV server port"
options:
  user: ""
  password: ""
  twofactorcode: null
  otptoken: null
  webdavport: 3005
  webdavprotocol: http
schema:
  user: email
  password: password
  twofactorcode: password?
  otptoken: password?
  webdavport: port
  webdavprotocol: list(http|https)
environment:
  INXT_USER: "{{ .user }}"
  INXT_PASSWORD: "{{ .password }}"
  INXT_TWOFACTORCODE: "{{ .twofactorcode }}"
  INXT_OTPTOKEN: "{{ .otptoken }}"
  WEBDAV_PORT: "{{ .webdavport }}"
  WEBDAV_PROTOCOL: "{{ .webdavprotocol }}"
startup: application
boot: auto
