name: "Internxt WebDAV"
description: "Mount your Internxt Drive as a WebDAV server for easy file access"
version: "1.0.8"
slug: "ix_webdav"
url: "https://github.com/ruepp-jenkins/hassio-addons"
startup: services
boot: auto
arch:
  - "amd64"
  - "aarch64"
init: false
backup_exclude:
  - "*"
ports:
  3006/tcp: null
ports_description:
  3006/tcp: "WebDAV server port (with authentification)"
options:
  user: ""
  password: ""
  twofactorcode: ""
  otptoken: ""
  webdav_user: "webdav"
  webdav_password: "replace-with-a-secure-password"
schema:
  user: email
  password: password
  twofactorcode: password?
  otptoken: password?
  webdav_user: str
  webdav_password: password
watchdog: "http://[HOST]:9000/"
