name: Internxt WebDAV
description: Mount your Internxt Drive as a WebDAV server for easy file access
version: 1.0.2
slug: internxt-webdav
url: https://github.com/internxt/cli
arch:
  - amd64
  - aarch64
init: false
ports:
  3005/tcp: 3005
ports_description:
  3005/tcp: WebDAV server port
options:
  INXT_USER: ""
  INXT_PASSWORD: ""
  INXT_TWOFACTORCODE: ""
  INXT_OTPTOKEN: ""
  WEBDAV_PORT: 3005
  WEBDAV_PROTOCOL: https
schema:
  INXT_USER: email
  INXT_PASSWORD: password
  INXT_TWOFACTORCODE: password
  INXT_OTPTOKEN: password
  WEBDAV_PORT: port
  WEBDAV_PROTOCOL: list(http|https)
startup: application
boot: auto
