name: "Internxt WebDAV"
description: "Mount your Internxt Drive as a WebDAV server for easy file access"
version: "1.0.4"
slug: "ix_webdav"
url: "https://github.com/MyUncleSam/hassio-addons"
startup: services
boot: auto
arch:
  - "amd64"
  - "aarch64"
init: false
ports:
  3006/tcp: null
ports_description:
  3006/tcp: "WebDAV server port (with authentification)"
options:
  user: ""
  password: ""
  twofactorcode: ""
  otptoken: ""
  webdavport: 3005
  webdavprotocol: http
  webdav_user: "webdav"
  webdav_password: "replace-with-a-secure-password"
schema:
  user: email
  password: password
  twofactorcode: password?
  otptoken: password?
  webdavport: port
  webdavprotocol: list(http|https)
  webdav_user: str
  webdav_password: password
watchdog: "http://[HOST]:3006/"
